# rAntiElytraTarget Configuration
# Authors: rdbull. & rest.d

# Maximum violations before ban is executed
max-violations: 10

# Time window in seconds for violation tracking
# After this time, violations reset
time-window-seconds: 3

# Minimum time between slot switches in milliseconds
# Switches faster than this are considered suspicious
min-switch-interval-ms: 50

# Number of consecutive rapid switches required to count as a violation
consecutive-switches-required: 5

# Alert message sent to staff members
# Placeholders: %player%, %count%, %max%
alert-message: "&c&l[Anti-Cheat] &e%player% &6suspicious elytra targeting detected! &7[%count%/%max%]"

# Command executed when max violations reached
# Placeholders: %player%, %reason%
ban-command: "ban %player% %reason%"

# Ban reason
ban-reason: "Elytra target hacks detected"

# Enable debug mode (logs detailed information)
debug-mode: false
